var c=document.querySelector(".modal__value");document.querySelector(".adjust-bar.adjust-bar_theme_temp").oninput=function(){c.innerHTML=0<this.value?"+"+this.value:this.value};var d=document.querySelector(".devices__paginator .paginator__arrow_left"),e=document.querySelector(".devices__paginator .paginator__arrow_right"),f=document.querySelector(".devices"),g=1;document.querySelector(".devices__paginator").classList.toggle("paginator_hide",7>document.querySelectorAll(".devices__panel").length);
e.addEventListener("click",function(){g+=1;d.classList.toggle("paginator__arrow_disabled",1===g);f.scroll({top:0,left:1366,behavior:"smooth"})});d.addEventListener("click",function(){1<g&&(--g,d.classList.toggle("paginator__arrow_disabled",1===g),f.scroll({top:0,left:-1366,behavior:"smooth"}))});var h,l;
function m(a){.42<a?a=.42:-.42>a&&(a=-.42);l=a;h=Math.floor(Math.abs(622.8*a+265)/53+26);document.querySelector(".modal_knob .modal__value").innerHTML="+"+h;document.querySelector(".knob__value").innerHTML="+"+h;document.querySelector(".knob__indicator").style.a=622.8*l+265+" 629";document.querySelector(".knob__arrow").style.transform="rotate("+360*l+"deg)"}
function n(a){var b=document.querySelector(".knob_center").getBoundingClientRect();b=[b.left+(b.right-b.left)/2,b.top+(b.bottom-b.top)/2];var k=[a.clientX,a.clientY];a.targetTouches&&a.targetTouches[0]&&(k=[a.targetTouches[0].clientX,a.targetTouches[0].clientY]);a=Math.atan2(k[1]-b[1],k[0]-b[0]);return a+=Math.PI/2}var p,q=null,r=null;function t(a){a.preventDefault();a.stopPropagation();a=n(a);p=!0;q=a;r=l}function u(){p=!1}
function v(a){if(p){var b=q;a=n(a);b=a-b;q=a;0>b&&(b+=2*Math.PI);b>Math.PI&&(b-=2*Math.PI);r=b=r+b/Math.PI/2;m(b)}}var w=document.querySelector(".knob-container");w.addEventListener("mousedown",t);document.addEventListener("mouseup",u);document.addEventListener("mousemove",v);w.addEventListener("touchstart",t);document.addEventListener("touchend",u);document.addEventListener("touchmove",v);m(0);
document.querySelectorAll(".modal_close").forEach(function(a){a.onclick=function(){document.querySelectorAll(".modal").forEach(function(a){a.classList.toggle("modal_open",!1);document.querySelector("body").style.overflow="auto"})}});var x={manual:-10,cold:0,warm:23,hot:30};
document.querySelectorAll(".modal__filter-item_temp").forEach(function(a){a.onclick=function(){document.querySelector(".adjust-bar_theme_temp").value=x[this.id];document.querySelector(".modal_temp .modal__value").innerHTML=0<x[this.id]?"+"+x[this.id]:x[this.id]}});function y(a){document.querySelector(a).classList.toggle("modal_open",!0);document.querySelector("body").style.overflow="hidden"}document.querySelectorAll(".panel_temp").forEach(function(a){a.onclick=function(){y(".modal_temp")}});
document.querySelectorAll(".panel_lamp").forEach(function(a){a.onclick=function(){y(".modal_light")}});document.querySelectorAll(".panel_floor").forEach(function(a){a.onclick=function(){y(".modal_knob")}});var z=document.querySelector(".scenarios__paginator .paginator__arrow_left"),A=document.querySelector(".scenarios__paginator .paginator__arrow_right"),B=document.querySelectorAll(".scenarios__page").length,C=document.querySelector(".scenarios"),D=1;
document.querySelector(".scenarios__paginator").classList.toggle("paginator_hide",9>=document.querySelectorAll(".scenarios__panel").length);A.addEventListener("click",function(){D<B&&(D+=1,A.classList.toggle("paginator__arrow_disabled",D===B),z.classList.toggle("paginator__arrow_disabled",1===D),C.scroll({top:0,left:645,behavior:"smooth"}))});
z.addEventListener("click",function(){1<D&&(--D,A.classList.toggle("paginator__arrow_disabled",D===B),z.classList.toggle("paginator__arrow_disabled",1===D),C.scroll({top:0,left:-645,behavior:"smooth"}))});var E=document.querySelector(".filter__select-button .button__text"),F=document.querySelectorAll(".filter__select-item"),G=document.querySelector(".filter__select-popup");document.querySelector(".filter__select-button").addEventListener("click",function(){G.classList.toggle("filter__select-popup_open")});
var H="";window.addEventListener("scroll",function(){H+=document.querySelectorAll("body")[0].offsetWidth;document.querySelector(".stats").innerHTML=H});F.forEach(function(a){a.addEventListener("click",function(a){document.querySelector("#"+a.target.dataset.group).checked=!0;F.forEach(function(a){return a.classList.toggle("filter__select-item_checked",!1)});a.target.classList.toggle("filter__select-item_checked",!0);G.classList.toggle("filter__select-popup_open",!1);E.innerText=a.target.innerText})});
document.querySelector(".menu__icon").addEventListener("click",function(){document.querySelector(".menu").classList.toggle("menu_open")});
